# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: BaseApp
    site_url: baseapp.local
    
    company_name: Kabisa ICT
    admin_email: admin@test.com
    
    support_name: Support
    support_email: support@test.com
    
    meta_keywords: "ruby on rails, tags, test"
    meta_description: "this is default. please change me."

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
